# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "AG Imkeller"
  description: "Group of Computational Immunology"
  image: img/logo_receptor.jpg
  
  favicon: img/logo_receptor.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo_receptor.png
    
    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Team"
        href: team/index.qmd
      - text: "Open Positions"
        href: openpositions/index.qmd
    
    # your social media handles
    right:
      - icon: twitter
        href: https://twitter.com/K_Imkeller
      - icon: github
        href: https://github.com/AGImkeller
      - icon: envelope-fill
        aria-label: email
        href: "mailto:ag.imkeller@gmail.com"  

  search: 
    location: navbar
    type: textbox
    
  page-footer: 
    left:
      - text: "Home"
        href: index.qmd
    right:
      - text: "Impressum"
        href: impressum.qmd

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
