# Open Positions

## Research technician - Quantitative Immunology

We are recruiting a research technician in quantitative immunology to contribute to our ongoing tumor-immunological research projects. The candidate should have experience in one or more of the following fields: tumor immunology, immunohistochemistry, flow cytometry, molecular biology, next generation sequencing, single-cell/spatial transcriptomics.

Please use the following link to apply: [AN: 1079-2023](https://short.sg/j/39413244) \


## Post-doctoral researcher - Quantitative Immunology

We are recruiting a postdoctoral researcher to investigate adaptive immune responses and organ-specific immune niches in solid tumors. The candidate will be responsible to design and conduct spatial omics experiments and to analyse and interpret resulting large scale data. Experimental techniques include flow cytometry, spatial transcriptomics, single-cell transcriptomics and multiplex imaging. 

**Your profile:**

- PhD in biology, molecular medicine, immunology, biophysics or related field
- Hands-on experience in flow cytometry and molecular biology. Experience with single-cell sequencing and/or omics-techniques are beneficial.
- Data analysis skills (Python or R) will be helpful and can be extended as part of the postdoctoral training.
- Strong interest in immunology or cancer biology.

Please use the following link to apply: [AN: 1080-2023](https://short.sg/j/39414511)


## Data scientist/bioinformatician

As a data scientist in quantitative immunology you will actively contribute to the software development and data analysis for our ongoing tumor-immunological research projects and closely interact with our clinical collaboration partners. 

**Your profile:**

- Hands-on experience in analysing (single-cell/spatial) transcriptomic data. 
- Proficiency linux operating systems and software development using R or python. 
- Strong interest in immunology or cancer biology.

Please use the following link to apply: [AN: 1081-2023](https://short.sg/j/39410906) \


## Student assistants (HiWi, 10-20h/week)

We offer computational jobs for student assistants to work in an exciting and interdisciplinary environment and directly contribute to our current research projects. Candidates should have hands-on experience in programming (R or python) and linux operating systems. The student assistant needs to be enrolled in a study program at a university in Germany.

**Research tasks:**

- software development and data analysis for our ongoing research projects
- development of interactive visualization tools for our collaborative research projects
- data management and software maintenance

Applications via email to [ag.imkeller | gmail.com](mailto:ag.imkeller@gmail.com) - please include a motivation letter, CV and transcripts of records.


## Thesis projects (BSc/MSc) and student internships

We offer internships, Bachelor’s and Master’s theses in different research areas of quantitative immunology. The research projects can be either experimental or computational. \

```{=html}
<div  style="margin: 30px; text-align: center;">
<a class="button-52" href="../projects/index.qmd" role="button" target="_blank" style="link-color: #495057; link-hover-decoration: none; color: #495057;">Our current research projects</a>
</div>

```

Applications via email to [ag.imkeller | gmail.com]() - please include a motivation letter, CV and transcripts of records.